### ISSUE TITLE
vf2和licheepi4a无法在五寸屏幕上适配，需要确认显示控制器是否存在限制。

### ISSUE THREAD

**Issue by ziyu04** [revyos/revyos#117]
硬件：微雪的800x480 五寸hdmi显示屏
问题描述： 可在Windows上正常显示分辨率，无法在licheepi4a上正常显示。

> 玄铁官网TH1520视频输出用户手册中显示无 800x480 分辨率彩条测试选项。

![Image](https://github.com/user-attachments/assets/622db0a5-ab27-4fb8-850f-9a5b10166b6a)

> 怀疑是显示控制器限制

**Comment by KevinMX** [comment]
补充提供的 edid hex dump:

```
00 FF FF FF FF FF FF 00 - 12 E5 00 21 50 2D 31 01 1C 13 01 03 81 2F 1A 78 - 2E 35 85 A6 56 48 9A 24 12 50 54 AF EF 00 01 01 - 01 01 01 01 01 01 01 01 01 01 01 01 01 01 3E 0D - 20 00 31 E0 37 10 2C 58 36 00 DC 0C 11 00 00 1E - 00 00 00 FF 00 30 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A - 0A 0A 00 00 00 FD 00 38 4B 1E 53 15 00 0A 20 20 - 20 20 20 20 00 00 00 FC 00 48 44 4D 49 0A 0A 0A - 0A 0A 0A 0A 0A 0A 01 F8 02 03 21 71 4E 06 07 02 - 03 15 96 11 12 13 04 14 05 1F 90 23 09 07 07 83 - 01 00 00 65 03 0C 00 10. 00 8C 0A D0 90 20 40 31 - 20 0C 40 55 00 B9 88 21 00 00 18 01 1D 80 18 71 - 1C 16 20 58 2C 25 00 B9 88 21 00 00 9E 01 1D 80 - D0 72 1C 16 20 10 2C 25 80 B9 88 21 00 00 9E 01 - 1D 00 BC 52 D0 1E 20 B8 28 55 40 B9 88 21 00 00 - 1E 02 3A 80 D0 72 38 2D 40 10 2C 45 80 B9 88 21 - 00 00 1E 00 00 00 00 D0
```

**Comment by Icenowy** [comment]
关于 edid dump -- 能否提供下 `hexdump -C /sys/class/drm/*/edid` 与 `cat /sys/class/drm/*/modes` 的内容？（后者是内核识别出的显示模式列表

**Comment by Icenowy** [comment]
什么文件都看不到……是否是邮件附件被 GitHub 忽略了？

**Comment by ziyu04** [comment]
> 什么文件都看不到……是否是邮件附件被 GitHub 忽略了？

已添加，您看一下。

**Comment by KevinMX** [comment]
```log
edid-decode (hex):

00 ff ff ff ff ff ff 00 12 e5 00 21 50 2d 31 01
1c 13 01 03 81 2f 1a 78 2e 35 85 a6 56 48 9a 24
12 50 54 af ef 00 01 01 01 01 01 01 01 01 01 01
01 01 01 01 01 01 3e 0d 20 00 31 e0 37 10 2c 58
36 00 dc 0c 11 00 00 1e 00 00 00 ff 00 30 0a 0a
0a 0a 0a 0a 0a 0a 0a 0a 0a 0a 00 00 00 fd 00 38
4b 1e 53 15 00 0a 20 20 20 20 20 20 00 00 00 fc
00 48 44 4d 49 0a 0a 0a 0a 0a 0a 0a 0a 0a 01 f8

02 03 21 71 4e 06 07 02 03 15 96 11 12 13 04 14
05 1f 90 23 09 07 07 83 01 00 00 65 03 0c 00 10
00 8c 0a d0 90 20 40 31 20 0c 40 55 00 b9 88 21
00 00 18 01 1d 80 18 71 1c 16 20 58 2c 25 00 b9
88 21 00 00 9e 01 1d 80 d0 72 1c 16 20 10 2c 25
80 b9 88 21 00 00 9e 01 1d 00 bc 52 d0 1e 20 b8
28 55 40 b9 88 21 00 00 1e 02 3a 80 d0 72 38 2d
40 10 2c 45 80 b9 88 21 00 00 1e 00 00 00 00 d0

----------------

Block 0, Base EDID:
  EDID Structure Version & Revision: 1.3
  Vendor & Product Identification:
    Manufacturer: DWE
    Model: 8448
    Serial Number: 20000080
    Made in: week 28 of 2009
  Basic Display Parameters & Features:
    Digital display
    DFP 1.x compatible TMDS
    Maximum image size: 47 cm x 26 cm
    Gamma: 2.20
    DPMS levels: Off
    RGB color display
    Default (sRGB) color space is primary color space
    First detailed timing is the preferred timing
  Color Characteristics:
    Red  : 0.6484, 0.3388
    Green: 0.2822, 0.6025
    Blue : 0.1425, 0.0703
    White: 0.3134, 0.3291
  Established Timings I & II:
    IBM     :   720x400    70.081663 Hz   9:5     31.467 kHz     28.320000 MHz
    DMT 0x04:   640x480    59.940476 Hz   4:3     31.469 kHz     25.175000 MHz
    DMT 0x05:   640x480    72.808802 Hz   4:3     37.861 kHz     31.500000 MHz
    DMT 0x06:   640x480    75.000000 Hz   4:3     37.500 kHz     31.500000 MHz
    DMT 0x08:   800x600    56.250000 Hz   4:3     35.156 kHz     36.000000 MHz
    DMT 0x09:   800x600    60.316541 Hz   4:3     37.879 kHz     40.000000 MHz
    DMT 0x0a:   800x600    72.187572 Hz   4:3     48.077 kHz     50.000000 MHz
    DMT 0x0b:   800x600    75.000000 Hz   4:3     46.875 kHz     49.500000 MHz
    Apple   :   832x624    74.551266 Hz   4:3     49.726 kHz     57.284000 MHz
    DMT 0x10:  1024x768    60.003840 Hz   4:3     48.363 kHz     65.000000 MHz
    DMT 0x11:  1024x768    70.069359 Hz   4:3     56.476 kHz     75.000000 MHz
    DMT 0x12:  1024x768    75.028582 Hz   4:3     60.023 kHz     78.750000 MHz
    DMT 0x24:  1280x1024   75.024675 Hz   5:4     79.976 kHz    135.000000 MHz
  Standard Timings: none
  Detailed Timing Descriptors:
    DTD 1:   800x480    60.004248 Hz   5:3     32.102 kHz     33.900000 MHz (476 mm x 268 mm)
                 Hfront   44 Hsync  88 Hback  124 Hpol P
                 Vfront    3 Vsync   6 Vback   46 Vpol P
    Display Product Serial Number: '0'
    Display Range Limits:
      Monitor ranges (GTF): 56-75 Hz V, 30-83 kHz H, max dotclock 210 MHz
    Display Product Name: 'HDMI'
  Extension blocks: 1
Checksum: 0xf8

----------------

Block 1, CTA-861 Extension Block:
  Revision: 3
  Basic audio support
  Supports YCbCr 4:4:4
  Supports YCbCr 4:2:2
  Native detailed modes: 1
  Video Data Block:
    VIC   6:  1440x480i   59.940060 Hz   4:3     15.734 kHz     27.000000 MHz
    VIC   7:  1440x480i   59.940060 Hz  16:9     15.734 kHz     27.000000 MHz
    VIC   2:   720x480    59.940060 Hz   4:3     31.469 kHz     27.000000 MHz
    VIC   3:   720x480    59.940060 Hz  16:9     31.469 kHz     27.000000 MHz
    VIC  21:  1440x576i   50.000000 Hz   4:3     15.625 kHz     27.000000 MHz
    VIC  22:  1440x576i   50.000000 Hz  16:9     15.625 kHz     27.000000 MHz (native)
    VIC  17:   720x576    50.000000 Hz   4:3     31.250 kHz     27.000000 MHz
    VIC  18:   720x576    50.000000 Hz  16:9     31.250 kHz     27.000000 MHz
    VIC  19:  1280x720    50.000000 Hz  16:9     37.500 kHz     74.250000 MHz
    VIC   4:  1280x720    60.000000 Hz  16:9     45.000 kHz     74.250000 MHz
    VIC  20:  1920x1080i  50.000000 Hz  16:9     28.125 kHz     74.250000 MHz
    VIC   5:  1920x1080i  60.000000 Hz  16:9     33.750 kHz     74.250000 MHz
    VIC  31:  1920x1080   50.000000 Hz  16:9     56.250 kHz    148.500000 MHz
    VIC  16:  1920x1080   60.000000 Hz  16:9     67.500 kHz    148.500000 MHz (native)
  Audio Data Block:
    Linear PCM:
      Max channels: 2
      Supported sample rates (kHz): 48 44.1 32
      Supported sample sizes (bits): 24 20 16
  Speaker Allocation Data Block:
    FL/FR - Front Left/Right
  Vendor-Specific Data Block (HDMI), OUI 00-0C-03:
    Source physical address: 1.0.0.0
  Detailed Timing Descriptors:
    DTD 2:   720x576    50.000000 Hz   5:4     31.250 kHz     27.000000 MHz (697 mm x 392 mm)
                 Hfront   12 Hsync  64 Hback   68 Hpol N
                 Vfront    5 Vsync   5 Vback   39 Vpol N
    DTD 3:  1920x1080i  60.000000 Hz  16:9     33.750 kHz     74.250000 MHz (697 mm x 392 mm)
                 Hfront   88 Hsync  44 Hback  148 Hpol P
                 Vfront    2 Vsync   5 Vback   15 Vpol P Vfront +0.5 Odd Field
                 Vfront    2 Vsync   5 Vback   15 Vpol P Vback  +0.5 Even Field
    DTD 4:  1920x1080i  50.000000 Hz  16:9     28.125 kHz     74.250000 MHz (697 mm x 392 mm)
                 Hfront  528 Hsync  44 Hback  148 Hpol P
                 Vfront    2 Vsync   5 Vback   15 Vpol P Vfront +0.5 Odd Field
                 Vfront    2 Vsync   5 Vback   15 Vpol P Vback  +0.5 Even Field
    DTD 5:  1280x720    50.000000 Hz  16:9     37.500 kHz     74.250000 MHz (697 mm x 392 mm)
                 Hfront  440 Hsync  40 Hback  220 Hpol P
                 Vfront    5 Vsync   5 Vback   20 Vpol P
    DTD 6:  1920x1080   50.000000 Hz  16:9     56.250 kHz    148.500000 MHz (697 mm x 392 mm)
                 Hfront  528 Hsync  44 Hback  148 Hpol P
                 Vfront    4 Vsync   5 Vback   36 Vpol P
Checksum: 0xd0
```

经过检查，EDID 信息中并未提供 800*480 显示模式，并非 RevyOS 一侧的问题。

请向您的屏幕供应商确认此显示器是否原生支持 800*480 模式。

Closing for now.

**Comment by Icenowy** [comment]
@KevinMX 看第一块区域的信息，是有 800x480 的；但有可能信息被扩展区域导致默认不是 800x480 ？

**Comment by ailunwowo** [comment]
> 话说有没有在目标板子上执行 xrandr 的结果呢？

xrandr: can't open display

**Comment by weilinfox** [comment]
我这边有一块微雪的 7inch HDMI LCD (B) Rev2.1，显示分辨率为 800x480 pixel，显示控制器为 TFP401APZP。

某种程度上复现了这个问题。

首先验证该显示屏可以正常工作。上电后使用 HDMI 连接松下 CF-SZ6， Archlinux 正常识别到显示屏并显示。

```
$ xrandr --display :0
Screen 0: minimum 320 x 200, current 2720 x 1200, maximum 16384 x 16384
eDP-1 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis) 264mm x 166mm
   1920x1200     60.08*+  59.88    59.95    48.06
   <此处省略余下的 mode>
DP-1 connected 800x480+1920+0 (normal left inverted right x axis y axis) 150mm x 100mm
   800x480       65.68*+
DP-2 disconnected (normal left inverted right x axis y axis)
```

添加 --verbose 参数后信息如下：

```
DP-1 connected 800x480+1920+0 (0x503) normal (normal left inverted right x axis y axis) 150mm x 100mm
        Identifier: 0x42
        Timestamp:  9696320
        Subpixel:   unknown
        Gamma:      1.0:1.0:1.0
        Brightness: 1.0
        Clones:    
        CRTC:       1
        CRTCs:      0 1 2
        Transform:  1.000000 0.000000 0.000000
                    0.000000 1.000000 0.000000
                    0.000000 0.000000 1.000000
                   filter: 
        EDID: 
                00ffffffffffff000481040001000000
                01110103800f0a000a00000000000000
                00000000000001010101010101010101
                010101010101800c208030e02d102830
                d3006c44000000180000001000000000
                00000000000000000000000000100000
                00000000000000000000000000000010
                00000000000000000000000000000017
        _KDE_SCREEN_INDEX: 2 
        HDCP Content Type: HDCP Type0 
                supported: HDCP Type0, HDCP Type1
        Content Protection: Undesired 
                supported: Undesired, Desired, Enabled
        Colorspace: Default 
                supported: Default, SMPTE_170M_YCC, BT709_YCC, XVYCC_601, XVYCC_709, SYCC_601, opYCC_601, opRGB, BT2020_CYCC, BT2020_RGB, BT2020_YCC, DCI-P3_RGB_D65, DCI-P3_RGB_Theater
        content type: No Data 
                supported: No Data, Graphics, Photo, Cinema, Game
        max bpc: 12 
                range: (6, 12)
        Broadcast RGB: Automatic 
                supported: Automatic, Full, Limited 16:235
        audio: auto 
                supported: force-dvi, off, auto, on
        subconnector: HDMI 
                supported: Unknown, VGA, DVI-D, HDMI, DP, Wireless, Native
        link-status: Good 
                supported: Good, Bad
        CTM:    1.000000 0.000000 0.000000
                0.000000 1.000000 0.000000
                0.000000 0.000000 1.000000
        CONNECTOR_ID: 107 
                supported: 107
        non-desktop: 0 
                range: (0, 1)
  800x480 (0x503) 32.000MHz -HSync -VSync *current +preferred
        h: width   800 start  840 end  888 total  928 skew    0 clock  34.48KHz
        v: height  480 start  493 end  496 total  525           clock  65.68Hz
```

附加信息，应当是只支持这一种显示分辨率：

```bash
$ hexdump /sys/class/drm/card1-DP-1/edid 
0000000 ff00 ffff ffff 00ff 8104 0004 0001 0000
0000010 1101 0301 0f80 000a 000a 0000 0000 0000
0000020 0000 0000 0000 0101 0101 0101 0101 0101
0000030 0101 0101 0101 0c80 8020 e030 102d 3028
0000040 00d3 446c 0000 1800 0000 1000 0000 0000
0000050 0000 0000 0000 0000 0000 0000 1000 0000
0000060 0000 0000 0000 0000 0000 0000 0000 1000
0000070 0000 0000 0000 0000 0000 0000 0000 1700
0000080
$ cat /sys/class/drm/card1-DP-1/modes 
800x480
```

连接荔枝派 4A 8G 版本后，上电无显示：

```bash
$ hexdump /sys/class/drm/card0-HDMI-A-1/edid
0000000 ff00 ffff ffff 00ff 8104 0004 0001 0000
0000010 1101 0301 0f80 000a 000a 0000 0000 0000
0000020 0000 0000 0000 0101 0101 0101 0101 0101
0000030 0101 0101 0101 0c80 8020 e030 102d 3028
0000040 00d3 446c 0000 1800 0000 1000 0000 0000
0000050 0000 0000 0000 0000 0000 0000 1000 0000
0000060 0000 0000 0000 0000 0000 0000 0000 1000
0000070 0000 0000 0000 0000 0000 0000 0000 1700
0000080
$ cat /sys/class/drm/card0-HDMI-A-1/modes
```

用其他显示屏登陆到桌面后再重新连接，获取 xrandr 输出可以看到没有可用的模式：

```
$ xrandr --display :0 --verbose
xrandr: Output HDMI-1 is not disconnected but has no modes
Screen 0: minimum 0 x 0, current 1024 x 768, maximum 4096 x 4096
HDMI-1 connected (normal left inverted right x axis y axis)
        Identifier: 0x3f
        Timestamp:  1065943
        Subpixel:   unknown
        Clones:    
        CRTCs:      1
        Transform:  1.000000 0.000000 0.000000
                    0.000000 1.000000 0.000000
                    0.000000 0.000000 1.000000
                   filter: 
        EDID: 
                00ffffffffffff000481040001000000
                01110103800f0a000a00000000000000
                00000000000001010101010101010101
                010101010101800c208030e02d102830
                d3006c44000000180000001000000000
                00000000000000000000000000100000
                00000000000000000000000000000010
                00000000000000000000000000000017
        max bpc: 0 
                range: (8, 16)
        link-status: Good 
                supported: Good, Bad
        non-desktop: 0 
                range: (0, 1)
```

若手动指定，则报 ``xrandr: Configure crtc 1 failed``：

```bash
$ xrandr --display :0 --newmode "800x480_65.68" 32.00 800 840 888 928 480 493 496 525 -hsync -hsync
$ xrandr --display :0 --addmode HDMI-1 800x480_65.68
$ xrandr --display :0 --output HDMI-1  --mode 800x480_65.68
xrandr: Configure crtc 1 failed
```

有一种情况可以显示，即只连接 HDMI 线，不上电。此时荔枝派 4A 识别到 HDMI 插入但无法读取 edid 信息，默认以 1024x768 输出：

```
$ hexdump /sys/class/drm/card0-HDMI-A-1/edid
$ cat /sys/class/drm/card0-HDMI-A-1/modes 
1024x768
800x600
800x600
848x480
640x480
$ xrandr --display :0 --verbose
Screen 0: minimum 0 x 0, current 1024 x 768, maximum 4096 x 4096
HDMI-1 connected 1024x768+0+0 (0x40) normal (normal left inverted right x axis y axis) 0mm x 0mm
        Identifier: 0x3f
        Timestamp:  1633160
        Subpixel:   unknown
        Gamma:      1.0:1.0:1.0
        Brightness: 1.0
        Clones:    
        CRTC:       1
        CRTCs:      1
        Transform:  1.000000 0.000000 0.000000
                    0.000000 1.000000 0.000000
                    0.000000 0.000000 1.000000
                   filter: 
        max bpc: 0 
                range: (8, 16)
        link-status: Good 
                supported: Good, Bad
        non-desktop: 0 
                range: (0, 1)
  1024x768 (0x40) 65.000MHz -HSync -VSync *current
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock  48.36KHz
        v: height  768 start  771 end  777 total  806           clock  60.00Hz
  800x600 (0x41) 40.000MHz +HSync +VSync
        h: width   800 start  840 end  968 total 1056 skew    0 clock  37.88KHz
        v: height  600 start  601 end  605 total  628           clock  60.32Hz
  800x600 (0x42) 36.000MHz +HSync +VSync
        h: width   800 start  824 end  896 total 1024 skew    0 clock  35.16KHz
        v: height  600 start  601 end  603 total  625           clock  56.25Hz
  848x480 (0x43) 33.750MHz +HSync +VSync
        h: width   848 start  864 end  976 total 1088 skew    0 clock  31.02KHz
        v: height  480 start  486 end  494 total  517           clock  60.00Hz
  640x480 (0x44) 25.175MHz -HSync -VSync
        h: width   640 start  656 end  752 total  800 skew    0 clock  31.47KHz
        v: height  480 start  490 end  492 total  525           clock  59.94Hz
```

再上电显示屏，显示屏将显示桌面的左上角部分。可见显示屏功能正常，但平常使用不可能这样。
